package de.tub.qds.rm.models.consts.repos;

import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;

import de.tub.qds.rm.models.values.ProcessorValue;
import de.tub.qds.rm.models.values.pks.ProcessorValuePK;

public interface ProcessorValueRepo extends JpaRepository<ProcessorValue, ProcessorValuePK> {
	
	Set<ProcessorValue> findByProcessorValueIdProcessorValueProcessorProcessorId(String processorId);
	Set<ProcessorValue> findByProcessorValueIdProcessorValueProcessorProcessorIdOrderByProcessorValueIdAsc(String processorId);
	Set<ProcessorValue> findByProcessorValueIdProcessorValueProcessorProcessorIdAndProcessorValueIdProcessorValueMeasurementId(String processorId, Long measurementId);
	Set<ProcessorValue> findByProcessorValueIdProcessorValueProcessorProcessorIdAndProcessorValueIdProcessorValueMeasurementIdOrderByProcessorValueIdProcessorValueTimestampAsc(String processorId, Long measurementId);
	ProcessorValue findTop1ByProcessorValueIdProcessorValueProcessorProcessorIdAndProcessorValueIdProcessorValueMeasurementIdOrderByProcessorValueIdProcessorValueTimestampAsc(String processorId, Long measurementId);
	ProcessorValue findTop1ByProcessorValueIdProcessorValueProcessorProcessorIdAndProcessorValueIdProcessorValueMeasurementIdOrderByProcessorValueIdProcessorValueTimestampDesc(String processorId, Long measurementId);
}
